"""Drug-class dictionaries used to harmonise prior-therapy variables (matched on upper-case substrings)."""

TAXANES = ["PACLITAXEL", "DOCETAXEL", "TAXOL", "TAXOTERE", "ABRAXANE", "CABAZITAXEL", "LAROTAXEL"]
ANTHRACYCLINES = ["DOXORUBICIN", "EPIRUBICIN", "DAUNORUBICIN", "IDARUBICIN", "ADRIAMYCIN",
                  "ADRIBLASTIN", "FARMORUBICIN", "PIXANTRONE", "MITOXANTRONE", "CAELYX", "MYOCET",
                  "PHARMORUBICIN", "LIPODOX"]
ENDOCRINE = ["TAMOXIFEN", "TOREMIFENE", "ANASTROZOLE", "LETROZOLE", "EXEMESTANE", "FULVESTRANT",
             "GOSERELIN", "LEUPRORELIN", "LEUPROLIDE", "TRIPTORELIN", "MEGESTROL", "MEDROXYPROGESTERONE",
             "ARIMIDEX", "FEMARA", "AROMASIN", "NOLVADEX", "FASLODEX", "ZOLADEX", "LUPRON", "RALOXIFENE",
             "AMINOGLUTETHIMIDE", "FORMESTANE"]
CHEMO = TAXANES + ANTHRACYCLINES + [
    "CYCLOPHOSPHAMIDE", "FLUOROURACIL", "5-FU", "CAPECITABINE", "XELODA", "METHOTREXATE", "VINORELBINE",
    "NAVELBINE", "GEMCITABINE", "GEMZAR", "CARBOPLATIN", "CISPLATIN", "IXABEPILONE", "ERIBULIN",
    "VINBLASTINE", "VINCRISTINE", "MITOMYCIN", "ETOPOSIDE", "IFOSFAMIDE", "THIOTEPA", "MELPHALAN",
    "TEGAFUR", "UFT", "S-1", "PEMETREXED", "IRINOTECAN", "TOPOTECAN", "OXALIPLATIN", "LIPOSOMAL",
    "CMF", "FEC", "FAC", "TRASTUZUMAB_EXCLUDED"]

HER2_TARGETED = ["TRASTUZUMAB", "HERCEPTIN", "LAPATINIB", "PERTUZUMAB"]


def has(name, lst) -> bool:
    if name is None:
        return False
    s = str(name).upper()
    return any(k in s for k in lst if not k.endswith("_EXCLUDED"))
